### ISSUE TITLE
转发的一个BUG，有完整配置文件

### ISSUE THREAD

**Issue by JarmoHu** [zhboner/realm#146]
中转机：
```toml
[log]
level = "warn"
output = "/var/log/realm.log"
[[endpoints]]
listen = "[::0]:27029"
remote = "[2605:6400:30:f9e1::1]:27029"
# remote_transport = "ws;host=amazon.com;path=/hqmhqm"
interface = "eth1"
listen_interface = "eth0"
through = "[2408:874f:b000:2d::1ce]"
```
落地机
```toml
[log]
level = "warn"
output = "/var/log/realm.log"
[[endpoints]]
listen = "[::0]:27029"
remote = "127.0.0.1:30180"
# listen_transport = "ws;host=amazon.com;path=/hqmhqm"
```
中转机日志：
```log
[2024-12-02][17:55:16][realm_core::tcp::socket][WARN][tcp]connect to [2605:6400:30:f9e1::1]:27029 as [2605:6400:30:f9e1::1]:27029: Connection refused (os error 111), try next ip
[2024-12-02][17:55:16][realm_core::tcp][ERROR][tcp][::ffff:122.189.149.212]:12192 => [2605:6400:30:f9e1::1]:27029, error: Connection refused (os error 111)
[2024-12-02][17:55:19][realm_core::tcp::socket][WARN][tcp]connect to [2605:6400:30:f9e1::1]:27029 as [2605:6400:30:f9e1::1]:27029: Connection refused (os error 111), try next ip
[2024-12-02][17:55:19][realm_core::tcp][ERROR][tcp][::ffff:122.189.149.212]:12196 => [2605:6400:30:f9e1::1]:27029, error: Connection refused (os error 111)
[2024-12-02][17:56:05][realm_core::tcp::socket][WARN][tcp]connect to [2605:6400:30:f9e1::1]:27029 as [2605:6400:30:f9e1::1]:27029: Connection refused (os error 111), try next ip
[2024-12-02][17:56:05][realm_core::tcp][ERROR][tcp][::ffff:122.189.149.212]:12253 => [2605:6400:30:f9e1::1]:27029, error: Connection refused (os error 111)
[2024-12-02][17:56:13][realm_core::tcp::socket][WARN][tcp]connect to [2605:6400:30:f9e1::1]:27029 as [2605:6400:30:f9e1::1]:27029: Connection refused (os error 111), try next ip
[2024-12-02][17:56:13][realm_core::tcp][ERROR][tcp][::ffff:122.189.149.212]:12271 => [2605:6400:30:f9e1::1]:27029, error: Connection refused (os error 111)
[2024-12-02][17:56:19][realm_core::tcp::socket][WARN][tcp]connect to [2605:6400:30:f9e1::1]:27029 as [2605:6400:30:f9e1::1]:27029: Connection refused (os error 111), try next ip
[2024-12-02][17:56:19][realm_core::tcp][ERROR][tcp][::ffff:122.189.149.212]:12280 => [2605:6400:30:f9e1::1]:27029, error: Connection refused (os error 111)
```
