### ISSUE TITLE
How does wss customize the path of the cer file and key file?

### ISSUE THREAD

**Issue by 669800** [zhboner/realm#55]
If I have cer and key files, how do I write them?

```

"remote_transport": "ws;host=example.com;path=/chat;tls;sni=example.com;insecure"

```

**Comment by zephyrchien** [comment]
See [libkaminari-tls-options](https://github.com/zephyrchien/kaminari#tls-options).

**Comment by 669800** [comment]
> See [libkaminari-tls-options](https://github.com/zephyrchien/kaminari#tls-options).

Does realm support all its features?

**Comment by zephyrchien** [comment]
Yep. Almost everything is handled by `libkaminari`, which accepts a formatted string then outputs handshake strategies(like client/server side ws/tls/wss).

**Comment by zephyrchien** [comment]
Realm is able to receive any of [tcp/ws/tls/wss] on one side, and send [tcp/ws/tls/wss] on the other side.

For example, receive `ws`, then send `tls`:

```toml
[[endpoints]]
listen = "127.0.0.1:10000"
remote = "127.0.0.1:20000"
listen_transport = "ws;host=example.com;path=/chat"
remote_transport = "tls;sni=example.com;insecure"
```
